server/djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL

    # path for about view
    path(route='about', view=views.about, name='about'),

    # path for contact us view
    path(route='contact', view=views.contact, name='contact'),

    # path for registration
    path(route='registration', view=views.registration_request, name='registration'),

    # path for login
    path(route='login', view=views.login_request, name='login'),

    # path for logout
    path(route='logout', view=views.logout_request, name='logout'),

    path(route='', view=views.get_dealerships, name='index'),

    # path for dealer reviews view
    path(route='dealer/<int:id>/',
         view=views.get_dealer_details, name='dealer_details'),

    # path for add a review view
    path(route='dealer/',
         view=views.add_review, name='add_review'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangoapp/models.py
from django.db import models
from django.utils.timezone import now


class CarMake(models.Model):
    name = models.CharField(null=False, max_length=30)
    description = models.CharField(null=False, max_length=100)

    def __str__(self):
        return "Name: " + self.name + ", Description: " + self.description


class CarModel(models.Model):
    car_make = models.ForeignKey(CarMake, on_delete=models.CASCADE)
    name = models.CharField(null=False, max_length=30)
    dealer_id = models.IntegerField(null=False)
    SEDAN = 'sedan'
    SUV = 'suv'
    WAGON = 'wagon'
    CAR_TYPE_CHOICES = [
        (SEDAN, 'Sedan'),
        (SUV, 'SUV'),
        (WAGON, 'Wagon'),
    ]
    type = models.CharField(
        null=False,
        max_length=5,
        choices=CAR_TYPE_CHOICES,
        default=SEDAN
    )
    year = models.DateField(null=False)

    def __str__(self):
        return "Name: " + self.name + ", Type: " + self.type + ", Year: " + str(self.year)


class CarDealer:
    def __init__(self, address, city, full_name, id, lat, long, short_name, st, zip):
        self.address = address
        self.city = city
        self.full_name = full_name
        self.id = id
        self.lat = lat
        self.long = long
        self.short_name = short_name
        self.st = st
        self.zip = zip

    def __str__(self):
        return "Dealer name: " + self.full_name


class DealerReview:
    def __init__(self, dealership, name, purchase, review, purchase_date, car_make, car_model, car_year, sentiment, id):
        self.dealership = dealership
        self.name = name
        self.purchase = purchase
        self.review = review
        self.purchase_date = purchase_date
        self.car_make = car_make
        self.car_model = car_model
        self.car_year = car_year
        self.sentiment = sentiment
        self.id = id

    def __str__(self):
        return "Review: " + self.review

server/djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.middleware.csrf import get_token
from django.shortcuts import (
    render,
    redirect
)
from django.contrib.auth import (
    login,
    logout,
    authenticate
)
from django.contrib import messages
from datetime import datetime
import logging
import json

from .restapis import (
    get_dealers_from_cf,
    get_dealer_reviews_from_cf,
    post_request,
)

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create an `about` view to render a static about page
def about(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/about.html', context)


# Create a `contact` view to return a static contact page
def contact(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/contact.html', context)

# Create a `login_request` view to handle sign in request


def login_request(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/index.html', context)
    elif request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("djangoapp:index")
        else:
            messages.error(request, "Invalid username or password.")
            return redirect("djangoapp:index")

# Create a `logout_request` view to handle sign out request


def logout_request(request):
    # Get the user object based on session id in request
    print("Log out the user `{}`".format(request.user.username))
    # Logout user in the request
    logout(request)
    # Redirect user back to course list view
    return redirect('djangoapp:index')

# Create a `registration_request` view to handle sign up request


def registration_request(request):
    context = {}
    # If it is a GET request, just render the registration page
    if request.method == 'GET':
        return render(request, 'djangoapp/registration.html', context)
    # If it is a POST request
    elif request.method == 'POST':
        # Get user information from request.POST
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            # Check if user already exists
            User.objects.get(username=username)
            user_exist = True
        except:
            # If not, simply log this is a new user
            logger.debug("{} is new user".format(username))
        # If it is a new user
        if not user_exist:
            # Create user in auth_user table
            user = User.objects.create_user(username=username,
                                            first_name=first_name,
                                            last_name=last_name,
                                            password=password)
            # Login the user and redirect to index
            login(request, user)
            return redirect("djangoapp:index")
        else:
            return render(request, 'djangoapp/registration.html', context)


def get_dealerships(request):
    if request.method == "GET":
        context = {}
        url = "http://localhost:3000/dealerships/get"

        # Get dealers from the URL
        dealerships = get_dealers_from_cf(url)

        context["dealers"] = dealerships

        return render(request, 'djangoapp/index.html', context)


# render the reviews of a dealer
def get_dealer_details(request, id):
    if request.method == "GET":
        url = "http://localhost:5000/api/get_reviews"
        dealer_reviews = get_dealer_reviews_from_cf(url, id)
        context = {
            "reviews": dealer_reviews
        }

        return render(request, 'djangoapp/dealer_details.html', context)



# submit a review
def add_review(request):

    if request.method == "GET":
        url = "http://localhost:3000/dealerships/get"
        cars = get_dealers_from_cf(url)
        context = {
            "cars": cars
        }
        return render(request, 'djangoapp/add_review.html', context)

    if request.method == "POST":
        csrf_token = get_token(request)

        url = "http://localhost:5000/api/post_review"
        review = {
            "id": 1114,
            "name": "Upkar Lidder",
            "dealership": 15,
            "review": "Great service!",
            "purchase": False,
            "another": "field",
            "purchase_date": "02/16/2021",
            "car_make": "Audi",
            "car_model": "Car",
            "car_year": 2021
        }

        headers = {
            "X-CSRFToken": csrf_token
        }

        status = post_request(url, json_payload=review, headers=headers)
        if status:
            return HttpResponse("Review added successfully")
        else:
            return HttpResponse("Failed to add review")
    else:
        return HttpResponse("Failed to add review")

server/djangoapp/templates/djangoapp/about.html
<html>
  <h1>
    Welcome to Best Cars dealership, home to the best cars in North America. We
    sell domestic and imported cars at reasonable prices.
  </h1>
</html>

server/djangoapp/templates/djangoapp/add_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>

</head>
    <body>
        <h1 class="text-center">Add a review about {{dealer.name}}</h1>
        <form method="post" action="{% url 'djangoapp:add_review' dealer_id %}">
            {% csrf_token %}
            <div class="form-group">

                <label for="content">Enter your review here:</label>
                <textarea class="form-control" id="content" name="content" rows="2" required></textarea>

                <label for="purchasecheck">Has purchased the car from this dealer? <span class="text-faded">(select purchased car information below if checked)</span></label>
                <input class="form-check-input" type="checkbox" name="purchasecheck" id="purchasecheck">

                <label for="car">Select your car (model, make, year):</label>
                <select name="car" id="car" class="form-select" required>
                    {% for car in cars %}
                    <option selected value={{car.id}}>{{car.name}}-{{car.make.name}}-{{ car.year|date:"Y" }}</option>
                    {% endfor %}
                </select>

                <label for="purchasedate">Enter the date of purchase:</label>
                <input class="date-own form-control" type="text" name="purchasedate" id="purchasedate">

                <button type="submit" class="btn btn-primary">Add Review</button>
            
    </body>

      <script type="text/javascript">
      $('.date-own').datepicker({
         format: 'mm/dd/yyyy'
       });
 </script>
</html>

server/djangoapp/templates/djangoapp/contact.html
<html>
<p>
    Address: 1234 Main St, San Francisco, CA 94123
</p>
<p>
    Phone: +1 415-123-4567  
</p>
</html>

server/djangoapp/templates/djangoapp/dealer_details.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Dealership Review</title>
    {% load static %}
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand text-primary" href="#">Dealership Review</a>
        </div>
        <ul class="nav navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'djangoapp:add_review' %}"
            >Add a Review</a
          >
          <li class="nav-item">
            <div class="rightalign">
              <div class="dropdown-content">
                <span class="dropbtn">Hello</span>
                <span class="mr-3">
                  {% if user.first_name == "" %} {{ user.username }} {% else %}
                  {{ user.first_name }} {% endif %}
                </span>
                <a
                  class="text-danger text-decoration-none"
                  href="{% url 'djangoapp:logout' %}"
                  >Logout</a
                >
              </div>
            </div>
          </li>
          {% else %}
          <li class="nav-item">
            <form
              class="form-inline"
              action="{% url 'djangoapp:login' %}"
              method="post"
            >
              {% csrf_token %}
              <div class="input-group">
                <input
                  type="text"
                  class="form-control"
                  placeholder="Username"
                  name="username"
                />
                <input
                  type="password"
                  class="form-control"
                  placeholder="Password"
                  name="psw"
                />
                <button class="btn btn-primary" type="submit">Login</button>
                <a
                  class="btn btn-link"
                  href="{% url 'djangoapp:registration' %}"
                  >Sign Up</a
                >
              </div>
            </form>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <!-- Add reviews as cards -->
    <div class="card-columns">
      <!-- for each review in reviews -->
      {% for review in reviews %}
      <h2 class="text-left text-primary mt-5">
        Reviews for {{ review.dealership }}
      </h2>

      <div class="card">
        <img
          class="card-img-left"
          src="{{ MEDIA_URL }}/emoji/positive.png"
          alt="Card image cap"
        />
        <div class="card-body">
          <h5 class="card-title">{{ review.name }}</h5>
          <p class="card-text">{{ review.id }}</p>
          <p class="card-text">{{ review.review }}</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </body>
</html>

server/djangoapp/templates/djangoapp/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Dealership Review</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link
      href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css"
      rel="stylesheet"
    />
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand text-primary" href="#">Dealership Review</a>
        </div>
        <ul class="nav navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <div class="rightalign">
              <div class="dropdown-content">
                <span class="dropbtn">Hello</span>
                <span class="mr-3">
                  {% if user.first_name == "" %} {{ user.username }} {% else %}
                  {{ user.first_name }} {% endif %}
                </span>
                <a
                  class="text-danger text-decoration-none"
                  href="{% url 'djangoapp:logout' %}"
                  >Logout</a
                >
              </div>
            </div>
          </li>
          {% else %}
          <li class="nav-item">
            <form
              class="form-inline"
              action="{% url 'djangoapp:login' %}"
              method="post"
            >
              {% csrf_token %}
              <div class="input-group">
                <input
                  type="text"
                  class="form-control"
                  placeholder="Username"
                  name="username"
                />
                <input
                  type="password"
                  class="form-control"
                  placeholder="Password"
                  name="psw"
                />
                <button class="btn btn-primary" type="submit">Login</button>
                <a
                  class="btn btn-link"
                  href="{% url 'djangoapp:registration' %}"
                  >Sign Up</a
                >
              </div>
            </form>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <!--Add a dealer table here -->
    <table class="table" id="table" data-filter-control="true">
      <thead>
        <tr>
          <th data-field="id">ID</th>
          <th data-field="name">Dealer Name</th>
          <th data-field="address">Address</th>
          <th data-field="city">City</th>
          <th data-field="state" data-filter-control="select">State</th>
          <th data-field="zip">Zip</th>
        </tr>
      </thead>
      <tbody>
        {% for dealer in dealers %}
        <tr>
          <td>{{dealer.id}}</td>
          <td><a href="{% url 'djangoapp:dealer_details' dealer.id %}">{{ dealer.full_name }}</a></td>
          <td>{{dealer.address}}</td>
          <td>{{dealer.city}}</td>
          <td>{{dealer.st}}</td>
          <td>{{dealer.zip}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>

  <!-- Javascript function to turn on filter control for the table -->
  <script>
    $(document).ready(function () {
      $("#table").bootstrapTable();
    });
    </script>
</html>

server/djangoapp/templates/djangoapp/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  {% load static %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <title>Sign Up</title>
</head>
<body>

<div class="container mt-5 mx-auto p-lg-5 p-4">
  <form action="{% url 'djangoapp:registration' %}" method="post">
    <h1 class="text-center">Sign Up</h1>
    <hr>

    <div class="form-group">
      <label for="username">User Name</label>
      <input type="text" class="form-control" placeholder="Enter User Name" name="username" required>
    </div>

    <div class="form-group">
      <label for="firstname">First Name</label>
      <input type="text" class="form-control" placeholder="Enter First Name" name="firstname" required>
    </div>

    <div class="form-group">
      <label for="lastname">Last Name</label>
      <input type="text" class="form-control" placeholder="Enter Last Name" name="lastname" required>
    </div>

    <div class="form-group">
      <label for="psw">Password</label>
      <input type="password" class="form-control" placeholder="Enter Password" name="psw" required>
    </div>

    {% csrf_token %}
    
    <button type="submit" class="btn btn-success btn-block">Sign Up</button>
  </form>
</div>

</body>
</html>